include: 'https://raw.githubusercontent.com/checkmarx-ltd/cx-flow/develop/templates/gitlab/v3/Checkmarx.gitlab-ci.yml'

stages:          # List of stages for jobs, and their order of execution
  - build
  - test

variables:
  CHECKMARX_BASE_URL: $CHECKMARX_BASE_URL
  CHECKMARX_USERNAME: $CHECKMARX_USERNAME
  CHECKMARX_PASSWORD: $CHECKMARX_PASSWORD
  GITLAB_TOKEN: $GITLAB_TOKEN
  #GITLAB_URL: http://mygitlab.mycompany.com
  #CX_FLOW_EXE: "java -Dhttp.proxyHost=myproxyserver.com -Dhttp.proxyPort=9595 -Dhttp.proxyUser=<proxy user> -Dhttp.proxyPassword=<proxy password> -jar /app/cx-flow.jar"

  CX_FLOW_ENABLED_VULNERABILITY_SCANNERS: "sast"
  #SCA_appUrl: https://eu.sca.checkmarx.net/ 
  #SCA_apiUrl: https://eu.api-sca.checkmarx.net
  #SCA_accessControlUrl: https://eu.platform.checkmarx.net

build-job:
  stage: build # This job runs in the build stage.
  script:
    - echo "Building..."
    - sleep 5 # We're demo'ing IaC scanning, nothing to build

sast-test-job:   # This job runs in the test stage.
  stage: test    # It only starts when the job in the build stage completes successfully.
  image: docker:latest
  services:
    - docker:dind
  script:
    - echo "Running sast."
    - echo "Running SCA."

